void getFile();
void getRestInfo();
int randomGen(int probOrLen);
void roundRobin();
void checkNewJob(int currentTime);
void doJob();
void removeQuantum(Job currentJob);
bool probIO(int genProb, Job currentJob);
void debugTest();
void jobDone(Job currentJob);