void getFile();
void getRestInfo();
int randomGen(int probOrLen);
void roundRobin();
void checkNewJob(int currentTime);
void doJob(int runTime);
void removeQuantum(Job currentJob, int runTime);
bool probIO(int genProb, Job currentJob);
void debugTest();
void jobDone(Job currentJob, int runTime);
void writeStats(int runTime);